version: "3.8"

services:
  server:
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
    restart: always

  client:
    container_name: client
    build:
      context: client
      dockerfile: Dockerfile
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
