version: "3.8"

services:
  lista:
    container_name: lista
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./config/:/app/config/
    ports:
      - "3000:3000"
