version: "3.8"

services:
  server_lista:
    container_name: server_lista
    build:
      context: server
      dockerfile: Dockerfile
    restart: always

  client_lista:
    container_name: client_lista
    build:
      context: client
      dockerfile: Dockerfile
    restart: always

  nginx_lista:
    container_name: nginx_lista
    image: nginx
    restart: always
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
